import { orders } from "@/data/orders";
import { channelLabels, type Order, type OrderChannel } from "@/types/order";
import type { ChannelRow, DashboardMetrics, ProductRow, ProfitRow, ReportMetrics, ReportRange, SalesRow } from "@/types/report";
const valid=(o:Order)=>o.status!=="CANCELLED";
const all=(range:ReportRange)=>orders.filter(valid);
export function getReportMetrics(range:ReportRange="today"):ReportMetrics { const rows=all(range); const revenue=rows.reduce((s,o)=>s+o.subtotal,0), discounts=rows.reduce((s,o)=>s+o.discountAmount,0), fees=rows.reduce((s,o)=>s+o.platformFee,0), cogs=revenue*.32, netRevenue=revenue-discounts-fees, grossProfit=netRevenue-cogs; return {revenue,orders:rows.length,aov:rows.length?revenue/rows.length:0,discounts,fees,netRevenue,cogs,grossProfit,margin:netRevenue?grossProfit/netRevenue*100:0,pending:rows.filter(o=>["NEW","ACCEPTED","PREPARING"].includes(o.status)).length,cancelled:orders.filter(o=>o.status==="CANCELLED").length}; }
export function getChannelReport(range:ReportRange="today"):ChannelRow[]{ const rows=all(range), total=rows.reduce((s,o)=>s+o.subtotal,0); return (Object.keys(channelLabels) as OrderChannel[]).map(channel=>{const x=rows.filter(o=>o.channel===channel), revenue=x.reduce((s,o)=>s+o.subtotal,0),discount=x.reduce((s,o)=>s+o.discountAmount,0),fees=x.reduce((s,o)=>s+o.platformFee,0);return {channel,orders:x.length,revenue,discount,fees,netRevenue:revenue-discount-fees,aov:x.length?revenue/x.length:0,share:total?revenue/total*100:0};}).filter(x=>x.orders); }
export function getProductReport(range:ReportRange="today"):ProductRow[]{const rows=all(range), total=rows.reduce((s,o)=>s+o.subtotal,0), map=new Map<string,ProductRow>(); rows.forEach(o=>o.items.forEach(i=>{const p=map.get(i.productId)||{productId:i.productId,name:i.productName,category:"Đồ uống",quantity:0,revenue:0,share:0,cogs:0,profit:0,margin:0};p.quantity+=i.quantity;p.revenue+=i.lineTotal;map.set(i.productId,p);}));return [...map.values()].map(p=>{p.share=total?p.revenue/total*100:0;p.cogs=p.revenue*.32;p.profit=p.revenue-p.cogs;p.margin=p.revenue?p.profit/p.revenue*100:0;return p;}).sort((a,b)=>b.revenue-a.revenue);}
export function getSalesReport(range:ReportRange="today"):SalesRow[]{const m=getReportMetrics(range);return [{label:"Hôm nay",orders:m.orders,revenue:m.revenue,discount:m.discounts,fees:m.fees,netRevenue:m.netRevenue,aov:m.aov}];}
export function getProfitReport(range:ReportRange="today"):ProfitRow[]{return [{label:"Hôm nay",...((m=>({revenue:m.revenue,discount:m.discounts,fees:m.fees,cogs:m.cogs,profit:m.grossProfit,margin:m.margin}))(getReportMetrics(range)))}];}
export function getDashboardMetrics(range:ReportRange="today"):DashboardMetrics{return {...getReportMetrics(range),channels:getChannelReport(range),products:getProductReport(range),sales:getSalesReport(range),recentOrders:all(range).slice(0,7)};}
export { channelLabels };
