"use client";

import { Check, Coffee, Loader2, MoreHorizontal, PackageOpen, ShoppingBag } from "lucide-react";
import { Badge, Button, Dialog, DialogContent, DialogTrigger, Skeleton, Toast, ToastDescription, ToastProvider, ToastTitle, ToastViewport } from "@/components/ui";
import { cn } from "@/lib/utils";

export function AppLogo() { return <div className="flex items-center gap-2.5"><div className="flex size-9 items-center justify-center rounded-md bg-primary text-primary-foreground"><Coffee size={19} /></div><div><div className="text-sm font-semibold leading-tight">T-San</div><div className="text-[11px] text-muted-foreground">Tea & Coffee</div></div></div>; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: React.ReactNode }) { return <header className="flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-[22px] font-semibold tracking-tight">{title}</h1>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</header>; }
const statusStyles = { success: "border-success/20 bg-success/10 text-success", warning: "border-warning/20 bg-warning/10 text-warning", danger: "border-danger/20 bg-danger/10 text-danger", info: "border-info/20 bg-info/10 text-info" };
export function StatusBadge({ status, children }: { status: keyof typeof statusStyles; children: React.ReactNode }) { return <Badge className={statusStyles[status]}><span className="mr-1.5 size-1.5 rounded-full bg-current" />{children}</Badge>; }
export function ChannelBadge({ channel }: { channel: "online" | "store" }) { return <Badge className="gap-1.5 bg-surface-secondary text-muted-foreground">{channel === "online" ? <ShoppingBag size={12} /> : <Coffee size={12} />}{channel === "online" ? "Online" : "Tại quầy"}</Badge>; }
export function EmptyState({ title = "Chưa có dữ liệu", description = "Dữ liệu sẽ xuất hiện ở đây khi có hoạt động mới." }: { title?: string; description?: string }) { return <div className="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed px-6 py-12 text-center"><PackageOpen className="text-muted-foreground" size={28} /><h3 className="text-sm font-semibold">{title}</h3><p className="max-w-xs text-xs leading-5 text-muted-foreground">{description}</p></div>; }
export function LoadingSkeleton() { return <div className="space-y-3"><Skeleton className="h-4 w-32" /><Skeleton className="h-9 w-full" /><Skeleton className="h-9 w-3/4" /></div>; }
export function ConfirmDialog({ trigger, title, description }: { trigger?: React.ReactNode; title: string; description: string }) { return <Dialog><DialogTrigger asChild>{trigger ?? <Button variant="outline">Xác nhận</Button>}</DialogTrigger><DialogContent><div className="space-y-4"><div><h2 className="text-base font-semibold">{title}</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">{description}</p></div><div className="flex justify-end gap-2"><Button variant="outline">Hủy</Button><Button><Check size={15} /> Xác nhận</Button></div></div></DialogContent></Dialog>; }
export function GlobalToast({ title = "Đã cập nhật", description = "Thao tác của bạn đã được ghi nhận." }: { title?: string; description?: string }) { return <ToastProvider><Toast defaultOpen><div className="flex items-start gap-3"><Check className="mt-0.5 text-success" size={16} /><div><ToastTitle className="text-sm font-medium">{title}</ToastTitle><ToastDescription className="mt-1 text-xs text-muted-foreground">{description}</ToastDescription></div><MoreHorizontal className="ml-auto text-muted-foreground" size={16} /></div></Toast><ToastViewport /></ToastProvider>; }
export function LoadingIcon({ className }: { className?: string }) { return <Loader2 className={cn("animate-spin", className)} size={16} />; }
