"use client";

import * as React from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { BarChart3, ChevronDown, Coffee, LayoutDashboard, LogOut, Menu, Package, Settings, ShoppingCart, Store, Users, X } from "lucide-react";
import { AppLogo } from "@/components/app-components";
import { Button, DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui";
import { useAuth } from "@/components/auth-context";

const nav = [{ href: "/dashboard", label: "Tổng quan", icon: LayoutDashboard }, { href: "/pos", label: "Bán hàng POS", icon: ShoppingCart }, { href: "#", label: "Đơn hàng", icon: Package }, { href: "#", label: "Sản phẩm", icon: Coffee }, { href: "#", label: "Khách hàng", icon: Users }, { href: "#", label: "Báo cáo", icon: BarChart3 }];

export function ManagementLayout({ children }: { children: React.ReactNode }) {
  const [open, setOpen] = React.useState(false);
  const pathname = usePathname();
  const router = useRouter();
  const { user, logout } = useAuth();
  const signOut = () => { logout(); router.replace("/login"); };
  return <div className="min-h-screen bg-background"><aside className={`fixed inset-y-0 left-0 z-40 flex w-64 flex-col border-r bg-surface transition-transform lg:translate-x-0 ${open ? "translate-x-0" : "-translate-x-full"}`}><div className="flex h-16 items-center justify-between border-b px-5"><AppLogo /><button className="rounded-md p-2 hover:bg-surface-secondary lg:hidden" onClick={() => setOpen(false)} aria-label="Đóng menu"><X size={18} /></button></div><div className="border-b px-4 py-4"><div className="mb-1 text-[11px] font-medium uppercase tracking-[0.14em] text-muted-foreground">Cửa hàng hiện tại</div><button className="flex w-full items-center justify-between rounded-md px-2 py-2 text-left text-sm font-medium hover:bg-surface-secondary"><span className="flex items-center gap-2"><Store size={15} className="text-primary" />{user?.store}</span><ChevronDown size={15} className="text-muted-foreground" /></button></div><nav className="flex flex-1 flex-col gap-1 p-4">{nav.map(({ href, label, icon: Icon }) => <Link key={label} href={href} onClick={() => setOpen(false)} className={`flex items-center gap-3 rounded-md px-3 py-2.5 text-sm transition-colors ${pathname === href ? "bg-primary-muted font-medium text-primary" : "text-muted-foreground hover:bg-surface-secondary hover:text-foreground"}`}><Icon size={17} />{label}</Link>)}<div className="mt-auto"><Link href="#" className="flex items-center gap-3 rounded-md px-3 py-2.5 text-sm text-muted-foreground hover:bg-surface-secondary"><Settings size={17} />Cài đặt</Link></div></nav></aside>{open && <button className="fixed inset-0 z-30 bg-foreground/20 lg:hidden" onClick={() => setOpen(false)} aria-label="Đóng menu" />}<div className="lg:pl-64"><header className="flex h-16 items-center justify-between border-b bg-surface px-4 sm:px-6"><Button variant="ghost" size="sm" className="lg:hidden" onClick={() => setOpen(true)} aria-label="Mở menu"><Menu size={18} /></Button><div className="hidden items-center gap-2 text-sm text-muted-foreground sm:flex"><Store size={15} />{user?.store}</div><DropdownMenu><DropdownMenuTrigger asChild><button className="flex items-center gap-2 rounded-md px-2 py-1.5 text-left hover:bg-surface-secondary"><span className="flex size-8 items-center justify-center rounded-full bg-primary-muted text-xs font-semibold text-primary">{user?.name.split(" ").slice(-1)[0].slice(0, 1)}</span><span className="hidden sm:block"><span className="block text-sm font-medium">{user?.name}</span><span className="block text-[11px] text-muted-foreground">{user?.role === "admin" ? "Quản trị viên" : "Nhân viên"}</span></span><ChevronDown size={14} className="text-muted-foreground" /></button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={signOut}><LogOut size={15} />Đăng xuất</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header><main>{children}</main></div></div>;
}
